# Docker Playground Configuration
# Add or modify images as needed

images:
  # Linux Distributions
  ubuntu-24:
    image: ubuntu:24.04
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Ubuntu 24.04 LTS (Noble Numbat)"
    category: linux
  
  ubuntu-22:
    image: ubuntu:22.04
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Ubuntu 22.04 LTS (Jammy Jellyfish)"
    category: linux
  
  ubuntu-20:
    image: ubuntu:20.04
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Ubuntu 20.04 LTS (Focal Fossa)"
    category: linux
  
  debian-12:
    image: debian:12
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Debian 12 (Bookworm)"
    category: linux
  
  debian-11:
    image: debian:11
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Debian 11 (Bullseye)"
    category: linux
  
  alpine:
    image: alpine:latest
    shell: /bin/sh
    keep_alive_cmd: tail -f /dev/null
    description: "Alpine Linux (Lightweight)"
    category: linux
  
  fedora:
    image: fedora:latest
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Fedora Linux"
    category: linux
  
  arch:
    image: archlinux:latest
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Arch Linux"
    category: linux

  # Programming Languages
  python-3.12:
    image: python:3.12
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Python 3.12 Runtime"
    category: programming
  
  python-3.11:
    image: python:3.11
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Python 3.11 Runtime"
    category: programming
  
  node-22:
    image: node:22
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Node.js 22 LTS"
    category: programming
  
  node-20:
    image: node:20
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Node.js 20 LTS"
    category: programming
  
  golang:
    image: golang:latest
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Go Programming Language"
    category: programming
  
  rust:
    image: rust:latest
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Rust Programming Language"
    category: programming
  
  openjdk-21:
    image: openjdk:21
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "OpenJDK 21"
    category: programming
  
  php-8.3:
    image: php:8.3
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "PHP 8.3"
    category: programming
  
  ruby:
    image: ruby:latest
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Ruby Language"
    category: programming

  # Databases
  postgres-16:
    image: postgres:16
    shell: /bin/bash
    keep_alive_cmd: postgres
    description: "PostgreSQL 16"
    category: database
    environment:
      POSTGRES_PASSWORD: playground
      POSTGRES_USER: playground
      POSTGRES_DB: playground
  
  mysql-8:
    image: mysql:8
    shell: /bin/bash
    keep_alive_cmd: mysqld
    description: "MySQL 8"
    category: database
    environment:
      MYSQL_ROOT_PASSWORD: playground
      MYSQL_DATABASE: playground
  
  mariadb:
    image: mariadb:latest
    shell: /bin/bash
    keep_alive_cmd: mariadbd
    description: "MariaDB"
    category: database
    environment:
      MYSQL_ROOT_PASSWORD: playground
      MYSQL_DATABASE: playground
  
  mongodb:
    image: mongo:latest
    shell: /bin/bash
    keep_alive_cmd: mongod
    description: "MongoDB"
    category: database
  
  redis:
    image: redis:latest
    shell: /bin/sh
    keep_alive_cmd: redis-server
    description: "Redis Cache"
    category: database

  # Web Servers
  nginx:
    image: nginx:latest
    shell: /bin/bash
    keep_alive_cmd: nginx -g 'daemon off;'
    description: "Nginx Web Server"
    category: webserver
    ports:
      - "8080:80"
  
  apache:
    image: httpd:latest
    shell: /bin/bash
    keep_alive_cmd: httpd-foreground
    description: "Apache HTTP Server"
    category: webserver
    ports:
      - "8081:80"

  # DevOps Tools
  docker-dind:
    image: docker:dind
    shell: /bin/sh
    keep_alive_cmd: dockerd-entrypoint.sh
    description: "Docker in Docker"
    category: devops
    privileged: true
  
  ansible:
    image: ansible/ansible:latest
    shell: /bin/bash
    keep_alive_cmd: sleep infinity
    description: "Ansible Automation"
    category: devops
  
  terraform:
    image: hashicorp/terraform:latest
    shell: /bin/sh
    keep_alive_cmd: tail -f /dev/null
    description: "Terraform IaC"
    category: devops

  # Testing & Development
  busybox:
    image: busybox:latest
    shell: /bin/sh
    keep_alive_cmd: sleep infinity
    description: "BusyBox (Minimal Unix)"
    category: utility
  
  curl:
    image: curlimages/curl:latest
    shell: /bin/sh
    keep_alive_cmd: sleep infinity
    description: "curl HTTP client"
    category: utility

# Global settings
settings:
  shared_volume_path: ./shared-volumes
  compose_file: docker-compose.yml
  network_name: playground-network