name: CI - Test CLI, TUI, and WebUI

on:
  push:
    branches: [develop, main]
    tags: [v*]  # Trigger su tag che iniziano con 'v' (es. v1.0.0)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Utile per tag e storia completa

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Come richiesto da server-webui.sh

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3  # Abilita Buildx per Docker avanzato

      - name: Install dependencies
        run: |
          # Installa dipendenze per TUI e WebUI
          sudo apt-get update
          sudo apt-get install -y whiptail expect lsof curl

      - name: Run CLI tests
        run: |
          chmod +x ./test-cli.sh
          ./test-cli.sh --non-interactive

      - name: Run WebUI tests
        run: |
          chmod +x ./test-webui.sh
          ./test-webui.sh